# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a9a3aa9deb5b8ce15508d7936c5b73c2c11c28c581b228ff05c39cb72ec6dfa3f8c6728b6b61bab847c0a2ab6f7655740adac711a467f4d970f9aa240caa15

test:
  secret_key_base: e5aeb098834f31acc275d6147cf0fece0982659b5989a550d17976371c060a64949f2f4b5764a8c34e7aecd2bcc4d6e1c83dd6a21c1e5db0c8ee42fc8e72ce35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
